import { AlphaDict } from './alpha-dict';

export const ALPHA_DICT_DEFAULT: AlphaDict = {
    'a': 'white',
    'b': 'white',
    'c': 'white',
    'd': 'white',
    'e': 'white',
    'f': 'white',
    'g': 'white',
    'h': 'white',
    'i': 'white',
    'j': 'white',
    'k': 'white',
    'l': 'white',
    'm': 'white',
    'n': 'white',
    'o': 'white',
    'p': 'white',
    'q': 'white',
    'r': 'white',
    's': 'white',
    't': 'white',
    'u': 'white',
    'v': 'white',
    'w': 'white',
    'x': 'white',
    'y': 'white',
    'z': 'white'
  }